//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLD.Tezos.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLD.Tezos.Client.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use as identity for daily transactions on modest funds.
        ///Quick and easy, but just a PIN....
        /// </summary>
        public static string AboutLightIdentity {
            get {
                return ResourceManager.GetString("AboutLightIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use for less frequent transactions on larger funds.
        ///Not so convenient, but pretty safe..
        /// </summary>
        public static string AboutStandardIdentity {
            get {
                return ResourceManager.GetString("AboutStandardIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown account.
        /// </summary>
        public static string Account_Unknown {
            get {
                return ResourceManager.GetString("Account_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is unknown to the network.
        /// </summary>
        public static string Account_UnknownLong {
            get {
                return ResourceManager.GetString("Account_UnknownLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use.
        /// </summary>
        public static string Account_Use {
            get {
                return ResourceManager.GetString("Account_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account activity.
        /// </summary>
        public static string AccountActivity {
            get {
                return ResourceManager.GetString("AccountActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account id.
        /// </summary>
        public static string AccountID {
            get {
                return ResourceManager.GetString("AccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activation.
        /// </summary>
        public static string Activation {
            get {
                return ResourceManager.GetString("Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code.
        /// </summary>
        public static string ActivationCode {
            get {
                return ResourceManager.GetString("ActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Identity.
        /// </summary>
        public static string AddIdentity {
            get {
                return ResourceManager.GetString("AddIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement.
        /// </summary>
        public static string AgreementTitle {
            get {
                return ResourceManager.GetString("AgreementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep cool. The alphanet has no genesis block yet. Your balance will be 0..
        /// </summary>
        public static string AlphanetDisclaimer {
            get {
                return ResourceManager.GetString("AlphanetDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount required.
        /// </summary>
        public static string AmountRequired {
            get {
                return ResourceManager.GetString("AmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string Approval_From {
            get {
                return ResourceManager.GetString("Approval_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        public static string Approval_Sign {
            get {
                return ResourceManager.GetString("Approval_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Approval_To {
            get {
                return ResourceManager.GetString("Approval_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total amount.
        /// </summary>
        public static string Approval_TotalAmount {
            get {
                return ResourceManager.GetString("Approval_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transferring.
        /// </summary>
        public static string Approval_Transferring {
            get {
                return ResourceManager.GetString("Approval_Transferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a backup file.
        /// </summary>
        public static string BackupByFile {
            get {
                return ResourceManager.GetString("BackupByFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup by mail.
        /// </summary>
        public static string BackupByMail {
            get {
                return ResourceManager.GetString("BackupByMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity backup | .
        /// </summary>
        public static string BackupFor {
            get {
                return ResourceManager.GetString("BackupFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT:
        ///
        ///1. Check that there is an attachment to this mail (Some mail clients have problems)
        ///2. Do NOT include your passphrase in this mail. Highly unsafe.
        ///
        ///
        ///Send it to yourself to have a backup in your inbox.
        ///It&apos;s safe to send this mail to any person, as long as you DO NOT reveal the PIN/Passphrase..
        /// </summary>
        public static string BackupMailBody {
            get {
                return ResourceManager.GetString("BackupMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your backup available from everywhere, send it to yourself.
        ///It&apos;s safe if only you know your PIN or passphrase..
        /// </summary>
        public static string BackupTip {
            get {
                return ResourceManager.GetString("BackupTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a backup target..
        /// </summary>
        public static string BackupVia {
            get {
                return ResourceManager.GetString("BackupVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you receive funds, please backup this identity.
        ///Without a backup, you could lose all the funds with this device..
        /// </summary>
        public static string BackupYourIdentity {
            get {
                return ResourceManager.GetString("BackupYourIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions may take up to a few minutes..
        /// </summary>
        public static string BePatient {
            get {
                return ResourceManager.GetString("BePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tezos.blue.
        /// </summary>
        public static string BlueStatement {
            get {
                return ResourceManager.GetString("BlueStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brain Wallet.
        /// </summary>
        public static string BrainWallet {
            get {
                return ResourceManager.GetString("BrainWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate.
        /// </summary>
        public static string CommitDelegate {
            get {
                return ResourceManager.GetString("CommitDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfer.
        /// </summary>
        public static string CommitTransfer {
            get {
                return ResourceManager.GetString("CommitTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create with PIN.
        /// </summary>
        public static string CreateLightIdentity {
            get {
                return ResourceManager.GetString("CreateLightIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important: Do not forget your PIN!
        ///This wallet will give you or your device&apos;s thief a hard time trying all combinations. But it&apos;s possible, so do not store large funds here..
        /// </summary>
        public static string CreateLightIdentityTip {
            get {
                return ResourceManager.GetString("CreateLightIdentityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create with passphrase.
        /// </summary>
        public static string CreateStandardIdentity {
            get {
                return ResourceManager.GetString("CreateStandardIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important: Do not lose your passphrase!
        ///If you lose or forget it, all your identity&apos;s funds are lost, forever.
        ///Write it down, exact to the letter, store it somewhere safe..
        /// </summary>
        public static string CreateStandardIdentityTip {
            get {
                return ResourceManager.GetString("CreateStandardIdentityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate.
        /// </summary>
        public static string Delegate {
            get {
                return ResourceManager.GetString("Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate funds.
        /// </summary>
        public static string Delegate_Title {
            get {
                return ResourceManager.GetString("Delegate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to delegate.
        /// </summary>
        public static string DelegateAmount {
            get {
                return ResourceManager.GetString("DelegateAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegated to.
        /// </summary>
        public static string DelegatedTo {
            get {
                return ResourceManager.GetString("DelegatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate to.
        /// </summary>
        public static string DelegateTo {
            get {
                return ResourceManager.GetString("DelegateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destination account.
        /// </summary>
        public static string DestinationAccount {
            get {
                return ResourceManager.GetString("DestinationAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destination account id.
        /// </summary>
        public static string DestinationAccountID {
            get {
                return ResourceManager.GetString("DestinationAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t lose your PIN or passphrase. Seriously.
        ///And make sure you find your backup from another device..
        /// </summary>
        public static string DontLoseCredential {
            get {
                return ResourceManager.GetString("DontLoseCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and Credentials.
        /// </summary>
        public static string EmailAndPassphrase {
            get {
                return ResourceManager.GetString("EmailAndPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter your PIN here.
        /// </summary>
        public static string EnterPIN {
            get {
                return ResourceManager.GetString("EnterPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter PIN to restore.
        /// </summary>
        public static string EnterPinToRestore {
            get {
                return ResourceManager.GetString("EnterPinToRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter PIN to sign.
        /// </summary>
        public static string EnterPINToSign {
            get {
                return ResourceManager.GetString("EnterPINToSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our services do not respond currently. 
        ///Please try again later..
        /// </summary>
        public static string Error_ServiceDown {
            get {
                return ResourceManager.GetString("Error_ServiceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeds max amount.
        /// </summary>
        public static string ExceedsMaxAmount {
            get {
                return ResourceManager.GetString("ExceedsMaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That went wrong....
        /// </summary>
        public static string Exit_Header {
            get {
                return ResourceManager.GetString("Exit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fees.
        /// </summary>
        public static string Fees {
            get {
                return ResourceManager.GetString("Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Unlock.
        /// </summary>
        public static string FirstIdentityLogin {
            get {
                return ResourceManager.GetString("FirstIdentityLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your identity will stay unlocked until your device goes to standby..
        /// </summary>
        public static string FirstIdentityLoginTip {
            get {
                return ResourceManager.GetString("FirstIdentityLoginTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Tezos network by creating your first identity. 
        ///No private information will be required, nor revealed..
        /// </summary>
        public static string FirstStep_P1 {
            get {
                return ResourceManager.GetString("FirstStep_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first steps.
        /// </summary>
        public static string FirstStep_Title {
            get {
                return ResourceManager.GetString("FirstStep_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from faucet.
        /// </summary>
        public static string FromFaucet {
            get {
                return ResourceManager.GetString("FromFaucet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to funded account.
        /// </summary>
        public static string FundedAccount {
            get {
                return ResourceManager.GetString("FundedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to funded by.
        /// </summary>
        public static string FundedBy {
            get {
                return ResourceManager.GetString("FundedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the public key hash above matches the one on your paper wallet before you import. Otherwise try other credentials..
        /// </summary>
        public static string FundraiserCheck {
            get {
                return ResourceManager.GetString("FundraiserCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Wallet (Fundraiser PDF).
        /// </summary>
        public static string FundraiserWallet {
            get {
                return ResourceManager.GetString("FundraiserWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        public static string IAgree {
            get {
                return ResourceManager.GetString("IAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identities.
        /// </summary>
        public static string Identities {
            get {
                return ResourceManager.GetString("Identities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identity account.
        /// </summary>
        public static string IdentityAccount {
            get {
                return ResourceManager.GetString("IdentityAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity already in wallet.
        /// </summary>
        public static string IdentityAlreadyKnown {
            get {
                return ResourceManager.GetString("IdentityAlreadyKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identity id.
        /// </summary>
        public static string IdentityID {
            get {
                return ResourceManager.GetString("IdentityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identity name.
        /// </summary>
        public static string IdentityName {
            get {
                return ResourceManager.GetString("IdentityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone who types in this exact text will have access to the identity. Choose carefully, something long and weird. Forget lyrics and literature..
        /// </summary>
        public static string ImportBrainTip {
            get {
                return ResourceManager.GetString("ImportBrainTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Brain Wallet.
        /// </summary>
        public static string ImportBrainWallet {
            get {
                return ResourceManager.GetString("ImportBrainWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./alphanet.sh client show identity my_identity -show-secret.
        /// </summary>
        public static string ImportEd25519Tip {
            get {
                return ResourceManager.GetString("ImportEd25519Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Test Identity.
        /// </summary>
        public static string ImportFaucet {
            get {
                return ResourceManager.GetString("ImportFaucet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Paper Wallet.
        /// </summary>
        public static string ImportFundraiserWallet {
            get {
                return ResourceManager.GetString("ImportFundraiserWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Keys.
        /// </summary>
        public static string ImportKeys {
            get {
                return ResourceManager.GetString("ImportKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impossible to guess.
        /// </summary>
        public static string ImpossibleToGuess {
            get {
                return ResourceManager.GetString("ImpossibleToGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal transfer.
        /// </summary>
        public static string InternalTransfer {
            get {
                return ResourceManager.GetString("InternalTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid passphrase. Try again..
        /// </summary>
        public static string InvalidPassphraseTryAgain {
            get {
                return ResourceManager.GetString("InvalidPassphraseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN. Try again..
        /// </summary>
        public static string InvalidPINTryAgain {
            get {
                return ResourceManager.GetString("InvalidPINTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sentence.
        /// </summary>
        public static string InvalidSentence {
            get {
                return ResourceManager.GetString("InvalidSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key data.
        /// </summary>
        public static string KeyData {
            get {
                return ResourceManager.GetString("KeyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Text.
        /// </summary>
        public static string KeyText {
            get {
                return ResourceManager.GetString("KeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-digit PIN.
        /// </summary>
        public static string LightIdentity {
            get {
                return ResourceManager.GetString("LightIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as backed up.
        /// </summary>
        public static string MarkAsBackedUp {
            get {
                return ResourceManager.GetString("MarkAsBackedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        public static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string mine {
            get {
                return ResourceManager.GetString("mine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic (15 words).
        /// </summary>
        public static string Mnemonic {
            get {
                return ResourceManager.GetString("Mnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive amounts only.
        /// </summary>
        public static string NegativeAmount {
            get {
                return ResourceManager.GetString("NegativeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to network fee.
        /// </summary>
        public static string NetworkFee {
            get {
                return ResourceManager.GetString("NetworkFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid amount.
        /// </summary>
        public static string NotAnAmount {
            get {
                return ResourceManager.GetString("NotAnAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fund a new account.
        /// </summary>
        public static string OriginateAccount {
            get {
                return ResourceManager.GetString("OriginateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passphrase.
        /// </summary>
        public static string Passphrase {
            get {
                return ResourceManager.GetString("Passphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the longer, the better....
        /// </summary>
        public static string PassphraseTip {
            get {
                return ResourceManager.GetString("PassphraseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending transactions.
        /// </summary>
        public static string PendingTransactions {
            get {
                return ResourceManager.GetString("PendingTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        public static string PIN {
            get {
                return ResourceManager.GetString("PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-digit PIN.
        /// </summary>
        public static string PIN4Digits {
            get {
                return ResourceManager.GetString("PIN4Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tezos.blue neither stores nor transmits any kind of information that identifies you personally.
        ///tezos.blue sends abstract usage telemetry and crash reports. This data has a retention time of 7 days..
        /// </summary>
        public static string PrivacyPromise {
            get {
                return ResourceManager.GetString("PrivacyPromise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tezos.blue.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Keys.
        /// </summary>
        public static string RandomKeys {
            get {
                return ResourceManager.GetString("RandomKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string ReceivedBy {
            get {
                return ResourceManager.GetString("ReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this release, we have
        ///
        ///- enabled a fallback mechanism for missed push messages
        ///- updated and frozen the encryption parameters for your keys
        ///
        ///As a result, all your former identities and backups are not accessible anymore, and the identities have been purged.
        ///You start with a clean slate..
        /// </summary>
        public static string ReleaseNote_0_2_5 {
            get {
                return ResourceManager.GetString("ReleaseNote_0_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        public static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat PIN.
        /// </summary>
        public static string RepeatPIN {
            get {
                return ResourceManager.GetString("RepeatPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore identity.
        /// </summary>
        public static string RestoreIdentity {
            get {
                return ResourceManager.GetString("RestoreIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No private key or other secret ever travels over the network.
        ///Secrets in device memory or storage are AES-encrypted with a passphrase of your choice.
        ///The wallet app has no access to your private keys in the underlying engine.
        ///
        ///For deeper insight into the engine&apos;s security concept, please look at the Security Reviewer&apos;s Guide in the GitHub repository tezos-blue/client..
        /// </summary>
        public static string SecurityPromise {
            get {
                return ResourceManager.GetString("SecurityPromise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Identity Type.
        /// </summary>
        public static string SelectIdentityType {
            get {
                return ResourceManager.GetString("SelectIdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to tezos.blue..
        /// </summary>
        public static string Service_Connected {
            get {
                return ResourceManager.GetString("Service_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Service_Connecting {
            get {
                return ResourceManager.GetString("Service_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to tezos.blue services. Will retry..
        /// </summary>
        public static string Service_ConnectingFailed {
            get {
                return ResourceManager.GetString("Service_ConnectingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network is currently cleaning up a cycle.
        ///Transactions are disabled for several minutes..
        /// </summary>
        public static string Service_CycleCleanup {
            get {
                return ResourceManager.GetString("Service_CycleCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service state changed.
        /// </summary>
        public static string Service_ServiceStateChanged {
            get {
                return ResourceManager.GetString("Service_ServiceStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service fee.
        /// </summary>
        public static string ServiceFee {
            get {
                return ResourceManager.GetString("ServiceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign account creation.
        /// </summary>
        public static string SignOrigination {
            get {
                return ResourceManager.GetString("SignOrigination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign transfer.
        /// </summary>
        public static string SignTransfer {
            get {
                return ResourceManager.GetString("SignTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source account.
        /// </summary>
        public static string SourceAccount {
            get {
                return ResourceManager.GetString("SourceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password or phrase.
        /// </summary>
        public static string StandardIdentity {
            get {
                return ResourceManager.GetString("StandardIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storage fee.
        /// </summary>
        public static string StorageFee {
            get {
                return ResourceManager.GetString("StorageFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total balance.
        /// </summary>
        public static string TotalBalance {
            get {
                return ResourceManager.GetString("TotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer tez.
        /// </summary>
        public static string Transfer_Title {
            get {
                return ResourceManager.GetString("Transfer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to foreign account.
        /// </summary>
        public static string Transfer_ToForeignAccount {
            get {
                return ResourceManager.GetString("Transfer_ToForeignAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to own account.
        /// </summary>
        public static string Transfer_ToOwnAccount {
            get {
                return ResourceManager.GetString("Transfer_ToOwnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfer amount.
        /// </summary>
        public static string TransferAmount {
            get {
                return ResourceManager.GetString("TransferAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string TransferredTo {
            get {
                return ResourceManager.GetString("TransferredTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software and services are provided &quot;as is&quot; without warranty of any kind. Use at your own risk..
        /// </summary>
        public static string UserPromise {
            get {
                return ResourceManager.GetString("UserPromise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you.
        /// </summary>
        public static string UserStatement {
            get {
                return ResourceManager.GetString("UserStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to tezos.blue.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
    }
}
